import { createCipheriv, createDecipheriv, randomBytes, scryptSync } from 'node:crypto'
import { Secret } from './secret.mjs'

// AES-256-GCM. Layout of a sealed buffer:
//   [ 0..11 ] nonce (12 bytes, fresh per seal)
//   [12..27 ] auth tag (16 bytes)
//   [28..   ] ciphertext
//
// GCM is authenticated: a tampered buffer fails to open instead of decrypting
// to garbage that downstream code might treat as a real token.

const NONCE_BYTES = 12
const TAG_BYTES = 16
const KEY_BYTES = 32

// Fixed salt: the master key is already high-entropy — generated by the deploy,
// never chosen by a human — so a per-value salt would only cost the ability to
// derive the same key twice without storing it somewhere.
const SALT = Buffer.from('linkyard.vault.v1')

export function deriveKey(masterKey) {
  if (typeof masterKey !== 'string' || masterKey.length < 32) {
    throw new TypeError('master key must be a string of at least 32 characters')
  }
  return scryptSync(masterKey, SALT, KEY_BYTES)
}

function assertKey(key) {
  if (!Buffer.isBuffer(key) || key.length !== KEY_BYTES) {
    throw new TypeError('key must be a 32-byte Buffer from deriveKey()')
  }
}

export function seal(key, plaintext) {
  assertKey(key)
  const value = plaintext instanceof Secret ? plaintext.reveal() : plaintext
  if (typeof value !== 'string' || value.length === 0) {
    throw new TypeError('seal requires a non-empty string or Secret')
  }
  const nonce = randomBytes(NONCE_BYTES)
  const cipher = createCipheriv('aes-256-gcm', key, nonce)
  const ciphertext = Buffer.concat([cipher.update(value, 'utf8'), cipher.final()])
  return Buffer.concat([nonce, cipher.getAuthTag(), ciphertext])
}

export function open(key, sealed) {
  assertKey(key)
  if (!Buffer.isBuffer(sealed) || sealed.length <= NONCE_BYTES + TAG_BYTES) {
    throw new TypeError('sealed value is not a valid vault buffer')
  }
  const nonce = sealed.subarray(0, NONCE_BYTES)
  const tag = sealed.subarray(NONCE_BYTES, NONCE_BYTES + TAG_BYTES)
  const ciphertext = sealed.subarray(NONCE_BYTES + TAG_BYTES)
  try {
    const decipher = createDecipheriv('aes-256-gcm', key, nonce)
    decipher.setAuthTag(tag)
    const plaintext = Buffer.concat([decipher.update(ciphertext), decipher.final()])
    return new Secret(plaintext.toString('utf8'))
  } catch {
    // Deliberately opaque: the caller learns that it failed, never why, and the
    // original error — which can carry key or buffer detail — is dropped here.
    throw new Error('unable to open sealed value')
  }
}

export function last4(value) {
  const s = value instanceof Secret ? value.reveal() : value
  if (typeof s !== 'string' || s.length < 8) {
    throw new TypeError('value is too short to expose a suffix')
  }
  return s.slice(-4)
}
